apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
    owner: solovev
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 2 
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.13.3
        ports:
        - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    run: vault
spec:
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
  selector:
    app: vault