apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    app: frontend
    owner: solovev
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: config

---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 443
    targetPort: 3000
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  REACT_APP_USERNAME: pavel
  REACT_APP_COMPANY_NAME: itmo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  tls:
    - hosts:
        - lab3.done
      secretName: secretka
  rules:
    - host: lab3.done
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-frontend
                port:
                  number: 443